{
    "name": "Evoluta Management - 5W2H",
    "version": "19.0.1.0.1",
    "summary": "5W2H que gera project.task",
    "author": "AlphaMec + Evoluta",
    "license": "LGPL-3",
    "depends": ["base", "project", "evoluta_core", "base_tier_validation"],
    "data": [
        "security/ir.model.access.csv",
        "security/rules.xml",
        "views/evoluta_5w2h_views.xml",
        "views/evoluta_porques_views.xml",
        "views/evoluta_risco_views.xml",
        "views/evoluta_raci_views.xml",
        "views/evoluta_ishikawa_views.xml",
        "views/evoluta_matriz_views.xml",
        "views/menus.xml",
        "data/demo_feira.xml",
    ],
    "installable": True,
    "application": False,
}
