[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/evoluta,/mnt/oca/helpdesk,/mnt/oca/tier-validation,/mnt/oca/server-tools,/mnt/oca/project,/mnt/oca/web,/mnt/oca/mis-builder,/mnt/oca/reporting-engine,/mnt/oca/server-ux,/mnt/oca/sign,/mnt/oca/queue
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
