{
    "name": "Evoluta Core",
    "version": "19.0.1.0.0",
    "summary": "Base: municipio, secretaria, permissoes",
    "author": "AlphaMec + Evoluta",
    "license": "LGPL-3",
    "depends": ["base", "project", "helpdesk_mgmt", "helpdesk_mgmt_sla"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/rules.xml",
        "views/evoluta_geo_views.xml",
        "views/evoluta_plano_views.xml",
        "views/evoluta_indicadores_views.xml",
        "views/menus.xml",
        "data/project_stages.xml",
        "data/onboarding.xml",
        "data/queue_runner_cron.xml",
    ],
    "installable": True,
    "application": False,
}
